# Generated by Django 4.1.4 on 2023-05-05 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(max_length=40, verbose_name='Тип товара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(verbose_name='Информация о товаре')),
                ('material', models.CharField(max_length=20, verbose_name='Материал')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('shape', models.CharField(max_length=20, verbose_name='Форма')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('photo_product', models.ImageField(upload_to='', verbose_name='Фотография товара')),
                ('photo_another', models.ImageField(blank=True, upload_to='', verbose_name='Другая фотография')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Размер')),
                ('size_two', models.CharField(blank=True, max_length=20, verbose_name='Размер_второй')),
                ('size_three', models.CharField(blank=True, max_length=20, verbose_name='Размер_третий')),
                ('size_four', models.CharField(blank=True, max_length=20, verbose_name='Размер_четвертый')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('available', models.CharField(choices=[('В наличие', 'В наличие'), ('Нет в наличие', 'Нет в наличие')], max_length=20, verbose_name='Наличие товара')),
                ('men', models.CharField(blank=True, choices=[('NEW', 'НОВИНКИ'), ('COAT', 'ПАЛЬТО'), ('SWEATER', 'СВИТЕРА'), ('HOODIE', 'ХУДИ'), ('SHIRT', 'РУБАШКИ'), ('T-SHIRT', 'ФУТБОЛКИ'), ('PANTS', 'БРЮКИ'), ('SNEAKERS', 'КРОССОВКИ'), ('SHOES', 'ОБУВЬ')], max_length=8, verbose_name='Мужчины')),
                ('women', models.CharField(blank=True, choices=[('NEW', 'НОВИНКИ'), ('COAT', 'ПАЛЬТО'), ('BLAZER', 'ПИДЖАКИ'), ('DRESS', 'ПЛАТЬЯ'), ('SHIRT', 'РУБАШКИ'), ('T-SHIRT', 'ФУТБОЛКИ'), ('SWEATER', 'СВИТЕРА'), ('PANTS', 'БРЮКИ'), ('JEANS', 'ДЖИНСЫ'), ('SNEAKERS', 'КРОССОВКИ'), ('SHOES', 'ОБУВЬ')], max_length=8, verbose_name='Женщины')),
                ('jewerlymen', models.CharField(blank=True, max_length=20, verbose_name='Украшения для мужчин')),
                ('jewerlywomen', models.CharField(blank=True, max_length=20, verbose_name='Украшения для женщин')),
                ('watchmen', models.CharField(blank=True, max_length=20, verbose_name='Часы для мужчин')),
                ('watchwomen', models.CharField(blank=True, max_length=20, verbose_name='Часы для женщин')),
                ('brand', models.CharField(blank=True, choices=[('AlexanderMcQueen', 'AlexanderMcQueen'), ('Balenciaga', 'Balenciaga'), ('Moncler', 'Moncler'), ('Off-White', 'Off-White'), ('Valentino', 'Valentino')], max_length=20, verbose_name='Бренд')),
                ('watch', models.CharField(blank=True, choices=[('CHOPARD', 'CHOPARD'), ('DEGRISOGONO', 'DEGRISOGONO'), ('GIRARDPERREGAUX', 'GIRARDPERREGAUX'), ('HUBLOT', 'HUBLOT'), ('BREITLING', 'BREITLING'), ('TAGHEUER', 'TAGHEUER'), ('TUDOR', 'TUDOR'), ('CHANEL', 'CHANEL')], max_length=20, verbose_name='Часы')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.productabout', verbose_name='О товаре')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.producttype', verbose_name='Тип товара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('photo_news', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('news', models.TextField(blank=True, verbose_name='Нововсти')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
